name: Deno

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
      fail-fast: true
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.17.0

      - name: Verify formatting
        if: matrix.os != 'windows-latest'
        run: deno fmt --config deno.json

      - name: Run linter
        run: deno lint --config deno.json

      - name: Run Test
        run: deno test